version: '2.1'

services:
  app:
    build: .
    ports:
      - "3000:3000" 
    links:
      - mongo
    depends_on:
      mongo:
        condition: service_healthy
    networks: 
      - all
    environment:
      MONGODB_URI: "mongodb://mongo:27017/ping"
      URL_API: "http://localhost:3000"
  mongo:
    image: bitnami/mongodb:3.6 
    ports:
    - "27017:27017"  
    volumes:
    - './data:/data/db'
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/ping --quiet
      interval: 30s
      timeout: 5s
      retries: 10
    networks: 
      - all
networks:
  all: