version: '2.1'

services:
  api:
    build: ./api
    ports:
      - "3000:3000" 
    links:
      - mongo
    depends_on:
      mongo:
        condition: service_healthy
    networks: 
      - all
    environment:
      MONGODB_URI: "mongodb://mongo:27017/ping"
  bot:
    build: ./bot
    networks: 
      - all
    environment:
      URL_API: "http://api:3000"
    command: tail -F anything
  mongo:
    image: bitnami/mongodb:3.6 
    ports:
    - "27017:27017"  
    volumes:
    - './data:/data/db'
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/ping --quiet
      interval: 30s
      timeout: 5s
      retries: 10
    networks: 
      - all
networks:
  all: